### ISSUE TITLE
watcher is not triggered automatically 

### ISSUE THREAD

**Issue by rkparkar** [lmangani/sentinl#532] opened 2018-09-04 09:06 UTC
1. Sentinl and Kibana version : 6.2.4

2. Issue description : i have created few watchers when i run them manually they work fine with correct output.  do receive alarm too (email). 
But the watcher isnt triggered at all. currently i have scheduled one watcher to run every 1 min while other to 2 mins 

3. Reproducing the issue step-by-step
create a watcher
have it enabled

4. Expected results vs. actual results
Expecteted result :
Watcher should get executed as per the schedule
actual result : 
Watcher isnt executed at all. 
checking kibana logs i find : "{"type":"log","@timestamp":"2018-09-04T09:01:25Z","tags":["debug","Sentinl","scheduler"],"pid":13473,"message":"no watchers found"}
"

5. Sample of data

6. Additional details
kibana logs gives : {"type":"log","@timestamp":"2018-09-04T09:01:25Z","tags":["debug","Sentinl","scheduler"],"pid":13473,"message":"no watchers found"}
Eventhough there are watchers present. and do work when executed manually

**Comment by rkparkar** [comment] 2018-09-04 09:38
as for now  i will paste whatever i have already checked. might be it is of use . 

kibana.yml  : 
{"type":"log","@timestamp":"2018-09-04T09:17:55Z","tags":["debug","Sentinl","scheduler"],"pid":13473,"message":"cluster disabled"}
{"type":"log","@timestamp":"2018-09-04T09:17:55Z","tags":["debug","Sentinl","scheduler"],"pid":13473,"message":"reloading watchers..."}
{"type":"log","@timestamp":"2018-09-04T09:17:55Z","tags":["debug","Sentinl","get_elasticsearch_client"],"pid":13473,"message":"auth via Kibana server elasticsearch plugin"}
{"type":"log","@timestamp":"2018-09-04T09:17:55Z","tags":["debug","Sentinl","get_elasticsearch_client"],"pid":13473,"message":"auth via Kibana server elasticsearch plugin"}
{"type":"log","@timestamp":"2018-09-04T09:17:55Z","tags":["debug","Sentinl","scheduler"],"pid":13473,"message":"no watchers found"}

![indices](https://user-images.githubusercontent.com/42961603/45023486-3358d000-b054-11e8-879b-d61b45cdb2b2.jpg)
![watcher_alarms](https://user-images.githubusercontent.com/42961603/45023487-33f16680-b054-11e8-8c39-988521ce38df.jpg)
![watcher_alarms-2018-09-4](https://user-images.githubusercontent.com/42961603/45023489-3489fd00-b054-11e8-8812-a2cecca74d51.jpg)

probably all this info can help .

**Comment by rkparkar** [comment] 2018-09-04 09:41
Any idea why the watchers are getting created in watcher_alrams-2018.09.04 ? and not in watcher_alarms?

**Comment by havlan** [comment] 2018-09-04 10:38
@rkparkar hmm, so it's saved to the watcher_alarms-yyyy.mm.dd index.
@sergibondarenko could you fill in here? Is this updated?

**Comment by rkparkar** [comment] 2018-09-04 11:43
an update , i did  try to change the kibana.yml to watcher_alarms-2018.09.04 but still the schedules are not triggerred. 
kibana log :
{"type":"log","@timestamp":"2018-09-04T11:42:55Z","tags":["debug","Sentinl","scheduler"],"pid":15330,"message":"no watchers found"}

**Comment by rkparkar** [comment] 2018-09-04 11:56
update : 
commented optional config in kibana.yml . The schedules are working now. 
probably will need to see what is wrong with the conf.

working yml snippet  :
sentinl:
  es:
    host: mfsprodait
    port: 9200
    #timefield: '@timestamp'
    #default_index: watcher
    #default_type: sentinl-watcher
    #alarm_index: watcher_alarms
    #alarm_type: sentinl-alarm
    #script_type: sentinl-script
  settings:
    email:
      active: true

**Comment by lmangani** [comment] 2018-09-04 12:06
@rkparkar we have an internal issue to resolve this - thanks for confirming the culprit!

**Comment by sergibondarenko** [comment] 2018-09-04 12:10
Here is the related issue https://github.com/sirensolutions/sentinl/issues/408. It will be fixed soon.

**Comment by rkparkar** [comment] 2018-09-04 12:10
regards!

**Comment by varun0002** [comment] 2019-05-03 13:40
Hello @sergibondarenko, Did we get this issue resolved? We are having exactly same issue on 5.6.X nd disabling all advanced parameters doesn't help us. Please let me know exact resolution for this.

**Comment by sergibondarenko** [comment] 2019-05-03 16:11
@varun0002 this issue was because @rkparkar specified `default_index: watcher` in the config. Because now Sentinl stores stuff in `.kibana` index by default. Basically Sentinl was unable to find watchers. After https://github.com/sirensolutions/sentinl/issues/408 you can specify a custom index. Enable Kibana debug and look at Sentinl messages. If you see a message like below, it means Sentinl  searches a wrong index.
```
{"type":"log","@timestamp":"2018-09-04T09:01:25Z","tags":["debug","Sentinl","scheduler"],"pid":13473,"message":"no watchers found"}
```

**Comment by varun0002** [comment] 2019-05-03 18:36
@sergibondarenko Thanks for quick response. Yes, I am getting no watcher found error & understand that index difference. My watchers are under .kibana/sentinl-watcher/ and looking at this I gave following entries in kibana.yml with no success:

Option 1: 
default_index: '.kibana'
default_type: 'sentinl-watcher'

Option 2:
default_index: '.kibana'
#default_type: 'sentinl-watcher'

I think the problem is that following is getting triggered during scheduler query.
  POST http://localhost:9200/.kibana/_search?size=50&from=0 

How can I get this to query below:
POST http://localhost:9200/.kibana/sentinl-watcher/_search?size=50&from=0

**Comment by varun0002** [comment] 2019-05-07 13:53
@sergibondarenko Could you please let me know if more details required. curl on http://localhost:9200/.kibana/_search?size=200&from=0 gives results but sentinl is giving "no watcher found" error. We are running kibana with searchgaurd.

**Comment by varun0002** [comment] 2019-05-14 13:36
@sergibondarenko I have tried multiple combinations to fix this but all in vain. I see you made number of changes in 5.6.x branch in Oct 2018. If I am not wrong, there seems to be issue in es_client under:
  async listWatchers(size) {
    try {
      const resp = await this.**find**({
        index: this._config.es.default_index,
        type: this._config.es.watcher_type,
        perPage: size || this._config.es.results,
      });
      resp.saved_objects = resp.saved_objects.map(flatAttributes);
      return resp;

the output of "let tasks = await client.listWatchers();" under "scheduler.js" is as follows:
{ page: 1, per_page: 50, total: 0, saved_objects: [] }

As I mentioned earlier, curl on .kibana index with same user (as for sentinl) returns appropriate values which indicates no issues with user access or authorization. We are stuck with this issue for long time now and unable to move forward with prod environment. Some review and help will be appreciated.

**Comment by varun0002** [comment] 2019-05-22 14:04
@sergibondarenko It looks like the issue with query. I raised PR #730 for your review. Please suggest if this is appropriate.

**Closed** 2020-07-30 10:19 UTC
